apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGO_URI: "your_mongodb_uri_here"
  JWT_ACCESS_SECRET: "your_jwt_access_secret_here"
  JWT_REFRESH_SECRET: "your_jwt_refresh_secret_here"
  BREVO_API_KEY: "your_brevo_api_key_here"
  CLOUDINARY_API_KEY: "your_cloudinary_api_key_here"
  CLOUDINARY_API_SECRET: "your_cloudinary_api_secret_here"
  CLOUDINARY_CLOUD_NAME: "your_cloudinary_cloud_name_here"
  FROM_EMAIL: "your_email_here"
  FRONTEND_URL: "http://localhost:3000"
  RESEND_API_KEY: "your_resend_api_key_here"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PASS: "your_smtp_password_here"
  SMTP_USER: "your_smtp_user_here"
  SUPABASE_KEY: "your_supabase_key_here"
  SUPABASE_URL: "your_supabase_url_here"
  GEMINI_API_KEY: "your_gemini_api_key_here"
